// config/features.ts
import { FeatureCard } from "@/types/feature";
import {
  Zap,
  Infinity,
  Clock,
  Download,
  Palette,
  History,
  RefreshCcw,
  Edit3,
  BarChart3,
  MapPin,
  Code,
  Beaker,
  ShieldCheck,
  Boxes,
  Headphones,
  HardDrive,
  Layers,
} from "lucide-react";

export const FEATURE_CARDS: (FeatureCard & {
  slug: string;
  heroTitle: string;
  heroSubtitle: string;
  benefits: string[];
  examples: string[];
  cta: string;
})[] = [
  {
    slug: "no-signup-required",
    title: "No Signup Required",
    icon: Zap,
    plans: ["free"],
    description: "Create QR codes instantly without creating an account.",
    helpsWith: "Removing friction and saving time.",
    whenToUse: "For quick, one-time or personal QR usage.",
    heroTitle: "Generate QR Codes Instantly",
    heroSubtitle: "No accounts. No forms. Just create and download.",
    benefits: [
      "Start in seconds",
      "No personal data required",
      "Perfect for quick tasks",
    ],
    examples: ["Sharing a WiFi password", "Linking to a personal website"],
    cta: "Create a QR Code Now",
  },

  {
    slug: "static-qr-codes",
    title: "Unlimited Static QR Codes",
    icon: Infinity,
    plans: ["free"],
    description: "Generate unlimited static QR codes with fixed destinations.",
    helpsWith: "Permanent links with zero maintenance.",
    whenToUse: "When the destination will never change.",
    heroTitle: "Permanent QR Codes That Never Change",
    heroSubtitle: "Simple, reliable QR codes for long-term use.",
    benefits: ["Unlimited creation", "No expiry", "Zero ongoing cost"],
    examples: ["Company website links", "Product packaging URLs"],
    cta: "Start Creating Static QRs",
  },

  {
    slug: "lifetime-validity",
    title: "Lifetime Validity",
    icon: Clock,
    plans: ["free"],
    description: "QR codes that never expire.",
    helpsWith: "Long-term reliability for printed materials.",
    whenToUse: "For posters, packaging, or signage.",
    heroTitle: "QR Codes That Last Forever",
    heroSubtitle: "Print once. Use forever.",
    benefits: ["No expiration risk", "Ideal for print", "Maintenance-free"],
    examples: ["Storefront posters", "Instruction manuals"],
    cta: "Generate Lifetime QR",
  },

  {
    slug: "high-resolution-downloads",
    title: "High-Resolution Downloads",
    icon: Download,
    plans: ["free"],
    description: "Download print-ready QR codes.",
    helpsWith: "Clear scanning across all formats.",
    whenToUse: "For banners, flyers, or product labels.",
    heroTitle: "Print-Ready QR Codes",
    heroSubtitle: "Crystal-clear QR codes at any size.",
    benefits: ["Sharp scans", "Multiple formats", "Perfect for print"],
    examples: ["Billboards", "Product labels"],
    cta: "Download Your QR",
  },

  {
    slug: "custom-qr-design",
    title: "Custom Design Options",
    icon: Palette,
    plans: ["free"],
    description: "Style QR codes to match your brand.",
    helpsWith: "Improving engagement and brand recall.",
    whenToUse: "When visual identity matters.",
    heroTitle: "Design QR Codes That Match Your Brand",
    heroSubtitle: "Your QR code should look as good as your product.",
    benefits: [
      "Brand consistency",
      "Higher scan rates",
      "Visual differentiation",
    ],
    examples: ["Brand-colored QRs", "Marketing campaigns"],
    cta: "Customize Your QR",
  },
  {
    slug: "qr-history-saved-locally",
    title: "QR History Saved Locally",
    icon: History,
    plans: ["free"],
    description: "Access recent QR codes on the same device.",
    helpsWith: "Quick reuse without login.",
    whenToUse: "For repeated usage on one device.",
    heroTitle: "Your Recent QR Codes, Always Handy",
    heroSubtitle:
      "Access previously generated QR codes instantly — no account required.",
    benefits: [
      "Reopen recently created QR codes",
      "No signup or login needed",
      "Faster repeat usage",
    ],
    examples: [
      "Reusing a payment QR multiple times a day",
      "Accessing a previously generated link QR",
    ],
    cta: "Generate a QR Code",
  },

  {
    slug: "dynamic-qr-codes",
    title: "Unlimited Dynamic QR Codes",
    icon: RefreshCcw,
    plans: ["pro"],
    description: "Change destinations after QR creation.",
    helpsWith: "Updating links without reprinting.",
    whenToUse: "For printed or large-scale campaigns.",
    heroTitle: "Update QR Destinations Anytime",
    heroSubtitle: "Change links even after your QR is printed.",
    benefits: [
      "Fix broken links instantly",
      "Run multiple campaigns",
      "Save reprint costs",
    ],
    examples: ["Restaurant menus", "Event landing pages"],
    cta: "Upgrade to Pro",
  },
  {
    slug: "unlimited-destination-edits",
    title: "Unlimited Destination Edits",
    icon: RefreshCcw,
    plans: ["pro"],
    description: "Edit the destination of dynamic QR codes anytime.",
    helpsWith: "Keeping QR codes relevant without reprinting.",
    whenToUse: "When links or content change frequently.",
    heroTitle: "Edit QR Destinations Without Limits",
    heroSubtitle:
      "Update where your QR leads — as many times as you want, even after printing.",
    benefits: [
      "Unlimited link updates",
      "No need to regenerate QR codes",
      "Perfect for evolving campaigns",
    ],
    examples: [
      "Updating campaign landing pages",
      "Switching offers or CTAs mid-campaign",
    ],
    cta: "Upgrade to Pro to Edit Destinations",
  },
  {
    slug: "advanced-qr-editor",
    title: "Advanced QR Editor",
    icon: Edit3,
    plans: ["pro"],
    description: "Advanced styling with logos and patterns.",
    helpsWith: "Creating standout branded QR codes.",
    whenToUse: "For marketing and promotions.",
    heroTitle: "Design QR Codes That Stand Out",
    heroSubtitle:
      "Go beyond basic QR codes with full control over design, branding, and style.",
    benefits: [
      "Add your logo to QR codes",
      "Customize patterns, colors, and shapes",
      "Maintain brand consistency across campaigns",
    ],
    examples: [
      "Branded QR codes on product packaging",
      "Marketing flyers with logo-embedded QRs",
    ],
    cta: "Upgrade to Pro for Advanced Design",
  },

  {
    slug: "qr-analytics",
    title: "Full Analytics Dashboard",
    icon: BarChart3,
    plans: ["pro"],
    description: "Track scans, trends, and performance.",
    helpsWith: "Measuring ROI and optimization.",
    whenToUse: "When data-driven decisions matter.",
    heroTitle: "Track Every QR Scan",
    heroSubtitle: "Know what works and optimize faster.",
    benefits: ["Scan trends", "Performance insights", "Better decisions"],
    examples: ["Campaign tracking", "Marketing attribution"],
    cta: "Unlock Analytics",
  },

  {
    slug: "scan-location-tracking",
    title: "Scan Location & Device Tracking",
    icon: MapPin,
    plans: ["pro"],
    description: "See where and how users scan.",
    helpsWith: "Understanding audience behavior.",
    whenToUse: "For marketing insights.",
    heroTitle: "Understand Your Audience",
    heroSubtitle: "See where, when, and how users scan.",
    benefits: ["Geo insights", "Device analytics", "Audience clarity"],
    examples: ["Regional campaigns", "Device optimization"],
    cta: "View Scan Insights",
  },
  {
    slug: "100mb-asset-storage",
    title: "100MB Asset Storage",
    icon: HardDrive,
    plans: ["pro"],
    description: "Store logos and brand assets securely.",
    helpsWith: "Consistent branding across QR designs.",
    whenToUse: "When managing multiple branded QR codes.",
    heroTitle: "Store Your Brand Assets in One Place",
    heroSubtitle:
      "Upload and reuse logos and brand visuals across all your QR codes.",
    benefits: [
      "Centralized asset management",
      "Faster QR creation",
      "Consistent brand identity",
    ],
    examples: [
      "Saving company logos for reuse",
      "Managing assets for multiple campaigns",
    ],
    cta: "Upgrade to Pro for Asset Storage",
  },
  {
    slug: "api-access",
    title: "API Support",
    icon: Code,
    plans: ["pro"],
    description: "Programmatic QR generation and control.",
    helpsWith: "Automation and integrations.",
    whenToUse: "When building apps or SaaS products.",
    heroTitle: "QR Codes via API",
    heroSubtitle: "Automate QR creation at scale.",
    benefits: ["Developer-friendly", "Fast integration", "Scalable automation"],
    examples: ["SaaS platforms", "Internal tools"],
    cta: "Read API Docs",
  },

  {
    slug: "ab-testing-qr",
    title: "A/B Testing on Dynamic QR",
    icon: Beaker,
    plans: ["enterprise"],
    description: "Split traffic between destinations.",
    helpsWith: "Improving conversion rates.",
    whenToUse: "For funnel optimization.",
    heroTitle: "Optimize with QR A/B Testing",
    heroSubtitle: "Let data decide what converts best.",
    benefits: [
      "Higher conversions",
      "Smart experimentation",
      "Traffic control",
    ],
    examples: ["Landing page tests", "Offer comparisons"],
    cta: "Talk to Sales",
  },
  {
    slug: "advanced-qr-analytics",
    title: "Advanced Analytics",
    icon: BarChart3,
    plans: ["enterprise"],
    description: "Deep insights into QR scan behavior.",
    helpsWith: "Understanding performance beyond basic metrics.",
    whenToUse: "When optimization and insights matter most.",
    heroTitle: "Understand Every Scan in Detail",
    heroSubtitle:
      "Go beyond scan counts with deeper insights into user behavior.",
    benefits: [
      "Detailed scan breakdowns",
      "Behavior and trend analysis",
      "Smarter decision-making",
    ],
    examples: [
      "Optimizing campaigns by region or device",
      "Identifying high-performing placements",
    ],
    cta: "Unlock Advanced Analytics",
  },
  {
    slug: "custom-qr-solutions",
    title: "Custom QR Solutions",
    icon: Layers,
    plans: ["enterprise"],
    description: "Tailored QR generation built for your business.",
    helpsWith: "Solving complex or unique QR use cases.",
    whenToUse: "When standard QR solutions aren’t enough.",
    heroTitle: "QR Codes Built Around Your Business",
    heroSubtitle:
      "We customize the QR experience to fit your workflows, systems, and scale.",
    benefits: [
      "Business-specific QR behavior",
      "Custom redirects and logic",
      "Enterprise-grade flexibility",
    ],
    examples: [
      "Internal operations QR systems",
      "Product or logistics QR workflows",
    ],
    cta: "Talk to Sales for Custom Solutions",
  },
  {
    slug: "controlled-expiry-qr",
    title: "Controlled-Expiry QRs",
    icon: ShieldCheck,
    plans: ["enterprise"],
    description: "Expire QR codes by time or scans.",
    helpsWith: "Security and access control.",
    whenToUse: "For events or internal access.",
    heroTitle: "QR Codes That Expire When You Decide",
    heroSubtitle: "Full control over access and duration.",
    benefits: ["Prevent misuse", "Time-based access", "Scan limits"],
    examples: ["Event tickets", "Internal resources"],
    cta: "Request Enterprise Access",
  },

  {
    slug: "bulk-qr-generation",
    title: "Bulk QR Generation",
    icon: Boxes,
    plans: ["enterprise"],
    description: "Generate thousands of QR codes at once.",
    helpsWith: "Saving time at scale.",
    whenToUse: "For inventory or asset tracking.",
    heroTitle: "Generate QR Codes in Bulk",
    heroSubtitle: "Thousands of QR codes in minutes.",
    benefits: ["Mass creation", "CSV upload", "Operational efficiency"],
    examples: ["Inventory tracking", "Logistics labeling"],
    cta: "Contact Sales",
  },
  {
    slug: "unlimited-asset-storage",
    title: "Unlimited Asset Storage",
    icon: Infinity,
    plans: ["enterprise"],
    description: "Unlimited storage for logos and images.",
    helpsWith: "Scaling branding without storage limits.",
    whenToUse: "For teams managing large asset libraries.",
    heroTitle: "Unlimited Storage for Brand Assets",
    heroSubtitle:
      "Store as many logos, images, and assets as your business needs.",
    benefits: [
      "No storage caps",
      "Supports large teams",
      "Scales with your business",
    ],
    examples: [
      "Managing assets for multiple brands",
      "Large-scale enterprise campaigns",
    ],
    cta: "Contact Sales for Enterprise Storage",
  },
  {
    slug: "host-with-your-domain",
    title: "Host with Your Domain",
    icon: ShieldCheck,
    plans: ["enterprise"],
    description:
      "Host dynamic QR redirects on your own domain or infrastructure.",
    helpsWith: "Full data privacy, compliance, and ownership.",
    whenToUse:
      "When your business requires complete control over QR traffic and data.",
    heroTitle: "Host QR Redirects on Your Own Domain",
    heroSubtitle:
      "Run dynamic QR redirects on your infrastructure for maximum privacy, control, and compliance.",
    benefits: [
      "Use your own domain for QR redirects",
      "Self-hosted infrastructure option",
      "Complete data ownership and privacy",
    ],
    examples: [
      "Enterprises with strict data compliance policies",
      "Organizations requiring on-prem or private cloud hosting",
    ],
    cta: "Talk to Sales About Self-Hosting",
  },

  {
    slug: "priority-support",
    title: "Priority Support",
    icon: Headphones,
    plans: ["enterprise"],
    description: "Faster, dedicated assistance.",
    helpsWith: "Minimizing downtime.",
    whenToUse: "When reliability is critical.",
    heroTitle: "Support That Moves Fast",
    heroSubtitle: "Dedicated help when your business depends on it.",
    benefits: ["Faster responses", "Dedicated assistance", "Peace of mind"],
    examples: ["Mission-critical campaigns", "Enterprise deployments"],
    cta: "Get Enterprise Support",
  },
];
