import { FeatureCard } from "@/types/feature";
import {
  Zap,
  Infinity,
  Clock,
  Download,
  Palette,
  History,
  RefreshCcw,
  Edit3,
  BarChart3,
  MapPin,
  HardDrive,
  Code,
  Layers,
  Beaker,
  ShieldCheck,
  Boxes,
  Headphones,
} from "lucide-react";

export const FEATURE_CARDS: FeatureCard[] = [
  {
    title: "No Signup Required",
    icon: Zap,
    plans: ["free"],
    description: "Create QR codes instantly without creating an account.",
    helpsWith: "Removing friction and saving time.",
    whenToUse: "For quick, one-time or personal QR usage.",
  },
  {
    title: "Unlimited Static QR Codes",
    icon: Infinity,
    plans: ["free"],
    description: "Generate unlimited static QR codes with fixed destinations.",
    helpsWith: "Permanent links with zero maintenance.",
    whenToUse: "When the destination will never change.",
  },
  {
    title: "Lifetime Validity",
    icon: Clock,
    plans: ["free"],
    description: "QR codes that never expire.",
    helpsWith: "Long-term reliability for printed materials.",
    whenToUse: "For posters, packaging, or signage.",
  },
  {
    title: "High-Resolution Downloads",
    icon: Download,
    plans: ["free"],
    description: "Download print-ready QR codes.",
    helpsWith: "Clear scanning across all formats.",
    whenToUse: "For banners, flyers, or product labels.",
  },
  {
    title: "Custom Design Options",
    icon: Palette,
    plans: ["free"],
    description: "Style QR codes to match your brand.",
    helpsWith: "Improving engagement and brand recall.",
    whenToUse: "When visual identity matters.",
  },
  {
    title: "QR History Saved Locally",
    icon: History,
    plans: ["free"],
    description: "Access recent QR codes on the same device.",
    helpsWith: "Quick reuse without login.",
    whenToUse: "For repeated usage on one device.",
  },
  {
    title: "Unlimited Dynamic QR Codes",
    icon: RefreshCcw,
    plans: ["pro"],
    description: "Change destinations after QR creation.",
    helpsWith: "Updating links without reprinting.",
    whenToUse: "For printed or large-scale campaigns.",
  },
  {
    title: "Advanced QR Editor",
    icon: Edit3,
    plans: ["pro"],
    description: "Advanced styling with logos and patterns.",
    helpsWith: "Creating standout branded QR codes.",
    whenToUse: "For marketing and promotions.",
  },
  {
    title: "Full Analytics Dashboard",
    icon: BarChart3,
    plans: ["pro"],
    description: "Track scans, trends, and performance.",
    helpsWith: "Measuring ROI and optimization.",
    whenToUse: "When data-driven decisions matter.",
  },
  {
    title: "Scan Location & Device Tracking",
    icon: MapPin,
    plans: ["pro"],
    description: "See where and how users scan.",
    helpsWith: "Understanding audience behavior.",
    whenToUse: "For marketing insights.",
  },
  {
    title: "API Support",
    icon: Code,
    plans: ["pro"],
    description: "Programmatic QR generation and control.",
    helpsWith: "Automation and integrations.",
    whenToUse: "When building apps or SaaS products.",
  },
  {
    title: "A/B Testing on Dynamic QR",
    icon: Beaker,
    plans: ["enterprise"],
    description: "Split traffic between destinations.",
    helpsWith: "Improving conversion rates.",
    whenToUse: "For funnel optimization.",
  },
  {
    title: "Controlled-Expiry QRs",
    icon: ShieldCheck,
    plans: ["enterprise"],
    description: "Expire QR codes by time or scans.",
    helpsWith: "Security and access control.",
    whenToUse: "For events or internal access.",
  },
  {
    title: "Bulk QR Generation",
    icon: Boxes,
    plans: ["enterprise"],
    description: "Generate thousands of QR codes at once.",
    helpsWith: "Saving time at scale.",
    whenToUse: "For inventory or asset tracking.",
  },
  {
    title: "Priority Support",
    icon: Headphones,
    plans: ["enterprise"],
    description: "Faster, dedicated assistance.",
    helpsWith: "Minimizing downtime.",
    whenToUse: "When reliability is critical.",
  },
];
