export const PRICING_PLANS = [
  {
    title: "Free",
    price: "$0",
    duration: "/month",
    ctaLabel: "Start Free",
    ctaLink: "/",
    features: [
      "No Signup Required",
      "Unlimited Static QR Codes",
      "Lifetime Validity",
      "High-Resolution Downloads",
      "Custom Design Options",
      "QR History Saved Locally",
    ],
  },
  {
    title: "Pro",
    price: "$5",
    duration: "/month",
    ctaLabel: "Get Started",
    ctaLink: "/login?redirect=/pricing&purchase=pro",
    features: [
      "All Free Features",
      "Unlimited Dynamic QR Codes",
      "Unlimited Destination Editing",
      "Advanced QR Editor",
      "Full Analytics Dashboard",
      "Scan Location & Device Tracking",
      "100MB Storage",
      "API Support",
    ],
  },
  {
    title: "Enterprise / Self-Hosting",
    price: "Contact Us",
    ctaLabel: "Contact Sales",
    ctaLink: "/contact-sales",
    features: [
      "All Pro Features",
      "Custom QR Solutions",
      "A/B Testing on Dynamic QR",
      "Advanced Analytics",
      "Controlled-Expiry QRs",
      "Bulk QR Generation",
      "Unlimited Storage",
      "Host with Your Domain",
      "Priority Support",
    ],
  },
];
